name: Build & Release

on:
  push:
    tags:
      - "v*"  # Runs only when a version tag (e.g., v1.0.0) is pushed

permissions:
  contents: write

jobs:
  release:
    name: Build for Jetson/RPi (aarch64)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y gcc-aarch64-linux-gnu

      - name: Install Rust target for aarch64
        run: rustup target add aarch64-unknown-linux-gnu

      - name: Set up cargo config for cross-compilation
        run: |
          mkdir -p .cargo
          echo '[target.aarch64-unknown-linux-gnu]' >> .cargo/config.toml
          echo 'linker = "aarch64-linux-gnu-gcc"' >> .cargo/config.toml

      - name: Build release binary
        run: cargo build --release --target aarch64-unknown-linux-gnu

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: doggo-display-aarch64
          path: target/aarch64-unknown-linux-gnu/release/doggo-display

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/aarch64-unknown-linux-gnu/release/doggo-display
